#! /bin/sh
# postinst script for liquidsoap
set -e

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
    ;;

    *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

if ! getent group liquidsoap >/dev/null 2>&1; then
    addgroup --system liquidsoap
fi

# Check for an account named 'liquidsoap'
if ! id liquidsoap >/dev/null 2>&1; then
    # Create the new system account
    adduser --system --disabled-password --disabled-login \
    --home /usr/share/liquidsoap --ingroup liquidsoap liquidsoap
fi

# Add 'liquidsoap' user to 'audio' group
usermod -a -G audio liquidsoap

# Add again /usr/share/liquidsoap if user was already created
if ! test -d /usr/share/liquidsoap; then
    mkdir /usr/share/liquidsoap
fi

# Fix directories ownership
chown -R root:root /usr/share/liquidsoap
chown -R liquidsoap:liquidsoap /var/log/liquidsoap
chown -R liquidsoap:liquidsoap /var/run/liquidsoap

# Automatically added by dh_installinit
if [ -x "/etc/init.d/liquidsoap" ]; then
	update-rc.d liquidsoap defaults >/dev/null
	invoke-rc.d liquidsoap start || exit $?
fi
# End automatically added section


exit 0

